SELECT FI.ID, FN.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FN ON FI.FISH_TYPE=FN.FISH_TYPE
WHERE 
    FI.LENGTH=(SELECT MAX(FII.LENGTH)
        FROM FISH_INFO FII
        WHERE FII.FISH_TYPE=FI.FISH_TYPE)
ORDER BY FI.ID ASC